# league_logo_urls.py
import unicodedata

def _norm(s: str) -> str:
    if s is None:
        return ""
    s = unicodedata.normalize("NFKD", str(s)).encode("ascii", "ignore").decode("ascii")
    return " ".join(s.strip().lower().split())

# =====================================================
# PASTE LEAGUE LOGO URLS ONLY
# Leave "" if you don't have it yet
# Example:
# "England 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/47.png",
# =====================================================

LEAGUE_LOGO_URLS = {
    "England 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/47.png",
    "England 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/48.png",
    "England 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/108.png",
    "England 4.": "https://images.fotmob.com/image_resources/logo/leaguelogo/109.png",
    "England 5.": "https://images.fotmob.com/image_resources/logo/leaguelogo/117.png",
    "England 6.": "https://images.fotmob.com/image_resources/logo/leaguelogo/8944.png",
    "England 7.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9084.png",
    "England 8.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9084.png",
    "England 9.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9084.png",
    "England 10.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9084.png",

    "Albania 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/260.png",
    "Argentina 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/112.png",
    "Armenia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/118.png",
    "Australia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/113.png",
    "Austria 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/38.png",
    "Austria 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/119.png",
    "Azerbaijan 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/262.png",
    "Belgium 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/40.png",
    "Belgium 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/264.png",
    "Bolivia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/144.png",
    "Bosnia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/267.png",
    "Brazil 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/268.png",
    "Brazil 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/8814.png",
    "Brazil 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/268.png",
    "Bulgaria 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/270.png",
    "Chile 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/273.png",
    "China 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/120.png",
    "Colombia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/274.png",
    "Costa Rica 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/121.png",
    "Croatia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/252.png",
    "Cyprus 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/136.png",
    "Czech 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/122.png",
    "Czech 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/253.png",
    "Denmark 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/46.png",
    "Denmark 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/85.png",
    "Ecuador 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/246.png",
    "Estonia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/248.png",
    "Estonia 2.": "",
    "Finland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/51.png",
    "France 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/53.png",
    "France 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/110.png",
    "France 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/8970.png",
    "Georgia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/439.png",
    "Germany 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/54.png",
    "Germany 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/146.png",
    "Germany 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/208.png",
    "Germany 4.": "https://images.fotmob.com/image_resources/logo/leaguelogo/512.png",
    "Greece 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/135.png",
    "Hungary 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/212.png",
    "Iceland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/216.png",
    "Israel 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/127.png",
    "Israel 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/128.png",
    "Italy 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/55.png",
    "Italy 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/86.png",
    "Italy 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/147.png",
    "Japan 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/223.png",
    "Japan 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/8974.png",
    "Kazakhstan 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/225.png",
    "Korea 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9080.png",
    "Korea 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/9116.png",
    "Kosovo 1.": "",
    "Latvia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/226.png",
    "Lithuania 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/228.png",
    "Malta 1.": "",
    "Mexico 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/230.png",
    "Moldova 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/231.png",
    "Netherlands 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/57.png",
    "Netherlands 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/111.png",
    "Northern Ireland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/129.png",
    "Norway 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/59.png",
    "Norway 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/203.png",
    "Paraguay 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/199.png",
    "Peru 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/131.png",
    "Poland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/196.png",
    "Portugal 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/61.png",
    "Portugal 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/185.png",
    "Portugal 3.": "",
    "Ireland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/185.png",
    "Ireland 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/218.png",
    "Romania 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/189.png",
    "Russia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/63.png",
    "Saudi 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/536.png",
    "Scotland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/64.png",
    "Scotland 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/123.png",
    "Serbia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/182.png",
    "Serbia 2.": "",
    "Slovakia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/176.png",
    "Slovenia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/173.png",
    "South Africa 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/537.png",
    "Spain 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/87.png",
    "Spain 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/140.png",
    "Spain 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/8968.png",
    "Sweden 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/67.png",
    "Sweden 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/168.png",
    "Sweden 3.": "https://images.fotmob.com/image_resources/logo/leaguelogo/169.png",
    "Switzerland 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/69.png",
    "Switzerland 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/163.png",
    "Tunisia 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/544.png",
    "Turkey 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/71.png",
    "Turkey 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/165.png",
    "Ukraine 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/441.png",
    "USA 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/130.png",
    "USA 2.": "https://images.fotmob.com/image_resources/logo/leaguelogo/10282.png",
    "Uruguay 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/161.png",
    "Venezuela 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/339.png",
    "Wales 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/116.png",
    "Morocco 1.": "https://images.fotmob.com/image_resources/logo/leaguelogo/530.png",
}

# Normalized lookup (only keeps filled URLs)
_LL = {_norm(k): str(v).strip() for k, v in LEAGUE_LOGO_URLS.items() if str(v).strip()}

def get_league_logo_url(league: str) -> str:
    return _LL.get(_norm(league), "")
